Speckle/Speckle.pq

Fixes error reported in the forum when receiving `commits` or `object` urls
https://speckle.community/t/powerbi-connector-not-showing-up/2076/20?u=alanrynne

fix: Fixes wrong implementation assignment and optional input removal

---

Speckle.pq
Speckle.query.pq
assets/resources.resx
speckle/Get.ByUrl.pqm

Modifies app credentials to connect to XYZ instead of latest.
Ensures read receipts are working in new function and tracked in MixPanel

Changes login from latest to XYZ

---

.circleci/config.yml

Changes usage from env vars in CircleCI to contexts

feat: using contexts in CI config

---

.vscode/extensions.json

Minor VSCode config changes, tbd after test with pavol if more is needed.

feat: Added extensions.json

---

.circleci/config.yml
README.md
Speckle.pq
assets/resources.resx
speckle/GetByUrl.pqm
speckle/api/Api.GetAllObjectChildren.pqm
speckle/helpers/CleanUpObjects.pqm
speckle/helpers/ParseStreamUrl.pqm

Just your normal update pre-stable release

Update `dev` with changes from `main`

---

tools/powerbi.iss

Just your normal update pre 2.19 stable release

Update `main` with changes from `dev`

---

.circleci/config.yml
.gitignore
src/powerbi-data-connector/Speckle.pq
src/powerbi-data-connector/Speckle.proj
src/powerbi-visual/package-lock.json
src/powerbi-visual/package.json
src/powerbi-visual/pbiviz.json
src/powerbi-visual/webpack.config.dev.ts
src/powerbi-visual/webpack.config.ts
tools/powerbi.iss

Adds Visual to installer.
Visual will end up in `USER/Documents/Power BI Desktop/Custom Visuals` following the same pattern that Data Exchange connector does.
It copies the file **unversioned**, meaning it will overwrite any previous visual that was installed by us.

feat: CNX-9628 Add visual to installer and CI script

---

speckle-powerbi.code-workspace

fixed extension path

---

src/powerbi-visual/package-lock.json
src/powerbi-visual/package.json
src/powerbi-visual/src/handlers/viewerHandler.ts
src/powerbi-visual/src/utils/viewerUtils.ts

Could potentially improve support for v3 connectors.
Fixed minor issues and tested for backwards compatibility only (hence why it's a draft still)
I'll merge as soon as I can confirm v3 commits

fix(CNX-382): Update viewer to latest version

---

src/powerbi-data-connector/Speckle.query.pq
src/powerbi-data-connector/speckle/api/GetRawData.pqm
src/powerbi-data-connector/speckle/api/GetRawJSON.pqm
src/powerbi-data-connector/speckle/api/GetStructuredData.pqm

renames the columns for aligning with the visual input names.

fix: align column and input names

---

src/powerbi-data-connector/speckle/api/GetStructuredData.pqm

fix: rename data column

---

src/powerbi-visual/src/plugins/viewer.ts
src/powerbi-visual/src/store/visualStore.ts

Fix(selection): isolate tooltip filtered data

---

GitVersion.yml

adding necessary yml for version detection

fix: adds GitVersion.yml

---

GitVersion.yml

this updates the gitversion.yml to change the label to beta

fix: update version label

---

.github/workflows/build_powerbi.yml

removes the code block which tries to set pq file versioning automatically

fix(data): version of the pq file

---

src/powerbi-data-connector/Speckle.query.pq
src/powerbi-data-connector/speckle/GetByUrl.pqm
src/powerbi-data-connector/speckle/api/GetStructuredData.pqm
src/powerbi-data-connector/speckle/api/SendToServer.pqm

adds a mechanism to check the server if there is a data already and cancels the send operation - optimizes the performance and let user to work with huge models.

fix (data connector): adds caching to data connector

---

.github/workflows/build_powerbi.yml

Bumped service to https://github.com/specklesystems/speckle-powerbi-service/releases/tag/0.4.0

Bumped Service to 0.4.0

---

src/powerbi-data-connector/speckle/api/SendToServer.pqm

adds root object id as a key to the check endpoint

fix (data connector): key added to the endpoint

---

src/powerbi-data-connector/speckle/api/SendToServer.pqm

Feat: post with id param

---

src/powerbi-data-connector/speckle/GetByUrl.pqm
src/powerbi-data-connector/speckle/api/GetModel.pqm
src/powerbi-data-connector/speckle/api/GetStructuredData.pqm
src/powerbi-data-connector/speckle/api/SendToServer.pqm

integrates data connector with new background service. basically the step 2 and 3.

feature (data connector): server integration

---

src/powerbi-visual/src/utils/mixpanel.ts

it is needed for better tracking distinction

Chore: add ui prop to mixpanel

---

src/powerbi-data-connector/speckle/api/GetModel.pqm

fixes a tree parsing logic for the url's with versions

fix(data connector): parsing source application from url with version

---

src/powerbi-data-connector/Speckle.pq

removes the beta flag from data source selection window

fix (data connector): removes beta flag

---

src/powerbi-visual/src/utils/matrixViewUtils.ts

Decreases the saved data by ~ %24 for revit receives which is majority

Feat(visual): cleanup data

---

src/powerbi-visual/capabilities.json
src/powerbi-visual/src/components/ViewerControls.vue
src/powerbi-visual/src/components/icons/ViewsIcon.vue
src/powerbi-visual/src/plugins/viewer.ts
src/powerbi-visual/src/store/visualStore.ts
src/powerbi-visual/src/utils/mixpanel.ts
src/powerbi-visual/src/visual.ts

https://github.com/user-attachments/assets/35a83af6-81ed-49e8-8400-d9a8aed443fd

Feat(visual): persistent camera position

---

src/powerbi-data-connector/speckle/api/GetUser.pqm

There was an issue to access public projects using anonymous credentials due to the problem that M language cannot convert null types to the Text types. 
I added null checks for anonymous credentials.

fix(data connector): adds null cehcks for anonymous user

---

.github/workflows/build_powerbi.yml

see https://linear.app/speckle/issue/CXPLA-177/clean-up-connector-installer-ci

refactor(ci): Update workflow to use new consolidated deployment workflow

---

src/powerbi-visual/src/utils/compression.ts

Tested and all good. The problem was in decompression if we have big files that were compressed with chunks.

Fix: saved big files

---

src/powerbi-data-connector/Speckle.pq
src/powerbi-data-connector/speckle/GetByUrl.pqm
src/powerbi-data-connector/speckle/api/CheckPermissions.pqm

Integrates the CanLoad query to check if user has the permisson to load.

feat(data connector): server-side permisson check integration

---

src/powerbi-visual/src/plugins/viewer.ts
src/powerbi-visual/src/utils/mixpanel.ts

adds the connector version to the info sent to mixpanel

feat (visual): send connector version to mixpanel

---

src/powerbi-visual/src/utils/matrixViewUtils.ts

was causing unhandled errors with some models

Fix: do not json stringify for model size

---

src/powerbi-data-connector/Speckle.pq

This PR adds the type registration of the helper functions.

fix: helper function registration

---

src/powerbi-data-connector/speckle/api/SendToServer.pqm

This pr adds the server url to exchange data to make sure token generation happens in the right server.

fix (data): adds server url to exchange data
