- Speckle/Speckle.pq
- Speckle/Speckle.query.pq
Adds read receipts call (with a similar approach to the matomo call).
> feat: Added receive receipts to PowerBI

- Speckle/Speckle.pq
Added pagination logic according to Microsofts own docs. Fixes https://github.com/specklesystems/admin/issues/221
It will fetch **all children of an object** in batches of 50 until it reaches the end.
Since we're actively removing all `DataChunks`, total count may not be exactly the same as the `totalChildrenCount` through the API, but I think that is ok for now.
> Adds pagination to object queries

- Speckle/Speckle.pq
Fixes issue #11 reported in the forum: https://speckle.community/t/power-bi-unable-to-receive-branch/2096
> Fix: Uses powerquery `buildQueryString` method to ensure branch name is url safe first

- .circleci/config.yml
- Speckle.pq
Fixes #27 
Adds ci build jobs for normal commits, and a `deploy` job for tagged commits that will upload the artifacts to the existing release.
This assumes the release already exists in GitHub, as we use them to create the tags that will trigger the CI builds.
> CI: Adds build and deploy configs

- speckle/api/Api.GetAllObjectChildren.pqm
- speckle/api/Api.GetObjectChildren.pqm
- speckle/helpers/CleanUpObjects.pqm
Fixes #24
- Swapped a call in `CleanUpObjects` that was using `List.RemoveItems` and doing a look-up by index; with a much faster `List.Select`. 10X FASTER
- Increased the amount of children being fetched per page to 1000. The reason for this is 2-fold. Makes less calls to the server, but it's also de default size of the `data preview`, so it will in theory only make 1 call in the initial load.
> Fixes slow behaviour in `Speckle.GetByUrl`

- Speckle.pq
- speckle/api/Api.REST.GetObject.pqm
- speckle/helpers/CleanUpObjects.pqm
- tests/api/api.rest.getobject.test.pq
- tests/getbyurl.test.pq
Adds call to `Speckle.Api.REST.Objects` to fetch all the children of a given object as a flat list.
This is way more performant than doing so by GraphQL, and requires just a single call, instead of a paginated series of calls to the children endpoint.
> Adds support for REST endpoint to get objects

- Speckle.pq
`Speckle.Revit.Parameters.ToNameValueRecord` will transform a parameter object so that it's a simplified record containing the `Name [InternalName]` and the actual value.
`Speckle.Utils.DynamicColumnExpand` will convert every single field in a table's record column into a new column in the table.
> feat: Adds new `ToNameValueRecord` function for revit params and `DynamicExpand` for table columns

- Speckle.pq
- speckle/helpers/ParseStreamUrl.pqm
This change specifically may benefit people that have a self-hosted server and haven't configured TLS so the URL scheme uses http.
> Parses the stream URL in a slightly more robust way.

- Speckle.pq
- Speckle.query.pq
- speckle/api/Api.GetModel.pqm
- speckle/helpers/ParseStreamUrl.pqm
Adds support for FE2 Urls in the form of:
- Model URL: `https://app.speckle.systems/projects/e2988234fb/models/MODEL_ID`
- Version URL: `https://app.speckle.systems/projects/e2988234fb/models/MODEL_ID@VERSION_ID`
Multi-model urls in the form of
`https://app.speckle.systems/projects/e2988234fb/models/MODELA@VERSIONA,MODELB,MODELC@VERSIONC`
> Adds Frontend2 URL Support for single model urls

- speckle/GetByUrl.pqm
- speckle/api/Api.GetAllObjectChildren.pqm
- speckle/helpers/CleanUpObjects.pqm
This issue was caused by the incorrect assumption that all commit objects would have detached children, which may not be the case when coming from scripts or SDKs without going through our connectors.
We'll also now ensure the parent object is included in the results as it is required to see the data if there are no detached children.
> fix: CNX-7606 Fixes missing `Data` column error

- speckle/helpers/ParseStreamUrl.pqm
Raises a new error when user inputs multi-model URL. Previously we were silently falling back to just the first model.
> CNX-9016: Raise error when user inputs multi-model URL

- tools/powerbi.iss
It doesn't need them since we signing the PQX was blocked.
Once we sign it we would need this too :)
> Fix admin rights in powerbi Installer

- tools/powerbi.iss
We were using userProfile env var instead of Innosetup's own defined constants.
Somehow they do some magic to figure out things better.
Lower admin rights to minimum as we don't need any more.
> fix: User Shell constant from Innosetup instead of ENV var from system

- tools/powerbi.iss
Ensures old mez file is deleted before copying over the new pqx file data connector
> fix: Ensure old .mez connector is removed upon installation

- README.md
- src/powerbi-data-connector/tests/api/api.fetch.test.pq
- src/powerbi-data-connector/tests/api/api.rest.getobject.test.pq
- src/powerbi-data-connector/tests/get.byurl.test.pq
- src/powerbi-data-connector/tests/getbyurl.test.pq
- src/powerbi-visual/capabilities.json
- remove reference to DO 1-click as this is deprecated
> chore(domains): update speckle.xyz to app.speckle.systems

- .github/workflows/build_powerbi.yml
Downloads the `Speckle.Services.PowerBi` zip (build by [speckle-powerbi-service](https://github.com/specklesystems/speckle-powerbi-service/blob/main/.github/workflows/release.yml)) and uploads as an artifact before triggering [connector-installers](https://github.com/specklesystems/connector-installers/blob/main/.github/workflows/build_powerbi.yml) ci.
> Pass service as artifact

- src/powerbi-data-connector/speckle/GetByUrl.pqm
- src/powerbi-data-connector/speckle/api/GetStructuredData.pqm
- src/powerbi-visual/capabilities.json
renames the input field of the visual and query column name from "Viewer Data ID" to "Version Object ID"
> fix: rename the input field

- src/powerbi-data-connector/Speckle.query.pq
- src/powerbi-data-connector/speckle/api/GetModel.pqm
- src/powerbi-data-connector/speckle/api/GetUser.pqm
- src/powerbi-data-connector/speckle/api/SendToServer.pqm
- src/powerbi-visual/capabilities.json
- src/powerbi-visual/src/plugins/viewer.ts
- src/powerbi-visual/src/store/visualStore.ts
- src/powerbi-visual/src/utils/hostAppSlug.ts
- src/powerbi-visual/src/utils/matrixViewUtils.ts
- src/powerbi-visual/src/utils/mixpanel.ts
- src/powerbi-visual/src/visual.ts
Data connector passes more rich data over `/download` post to log it into dictionary for visual, then visual calls the `/user-info` to be able to track receive event.
> Feat(mixpanel): get user info from service

- src/powerbi-data-connector/speckle/api/GetStructuredData.pqm
Currently we're filtering the objects by checking their applicationId field. If it doesn't exist or equals to null, we're filtering them out. The initial idea was to remove DataChunks from the query. 
But that caused some issues with models that created by SDK's directly and some connectors like Grasshopper and Blender. For example a model created with specklepy and everything is attached under one collection, receives and empty table at the moment.
After the change we can receive it as one row.
Therefore, in this PR, I've changed the filtering logic to directly checking the speckle type. 
This change also brings some other object types that we were filtering out. Like if I receive data from a model with TeklaObjects, in current logic I only get the Tekla DataObjects.
After the changes …
> fix (data connector): object filtering logic

- src/powerbi-data-connector/Speckle.query.pq
- src/powerbi-data-connector/speckle/api/GetUser.pqm
The source of "We reached end of the buffer" indicates that desktop service is returning an empty or malformed JSON. 
In this case for the private projects, we were not setting the token right. This PR is adding a switch case to check if the token passed through OAuth or directly. For Link Sharable projects, we're setting an empty string as a token.
> fix(data connector): reaching the end of the buffer

- src/powerbi-data-connector/speckle/api/GetWorkspace.pqm
adds a null check for workspace info. fixes the following issue.
https://linear.app/speckle/issue/CNX-1931/trying-to-load-a-personal-project-results-in-error
> fix (data): personal projects returns workspaceId null

- .github/workflows/deploy.yml
- .github/workflows/pr.yml
Previously, we only had CI for deployment
This PR adds a simple workflow that builds ensures the connector and visual build on every PR
> CI: pull request build

- src/powerbi-data-connector/speckle/api/GetStructuredData.pqm
This PR expands the exclusion logic to exclude `displayValue` from data connector. We really don't need them in the data side and also in this way the model is leaner and avoids duplication of breps and meshes.
> feat(data): exclude displayValue in data 

- src/powerbi-data-connector/Speckle.pq
- src/powerbi-data-connector/speckle/api/Objects.MaterialQuantities.pqm
This PR adds a new helper function: Speckle.Objects.MaterialQuantities
This functions allows quick and easy way to extract material quantities. It is intended to be used in "Add Column" flow, so it interacts with individual records, not tables.
**Inputs:**
**objectRecord** (record): The source record.
**outputAsList** (optional logical): If true, returns the result as a list (then user can expand list column themselves); otherwise, as a record (default).
**Returns**:
If the input record contains the "Material Quantities" property, the function returns it either as a record or a list, depending on the outputAsList parameter. If the property is not found, the function returns null.
**Example Usage**
```m
Speckle.Objects.MaterialQuantities(someObjectRecord) // returns the Material Quantities …
```
> object material quantities added

- src/powerbi-visual/src/components/ViewerWrapper.vue
- src/powerbi-visual/src/extensions/FilteredSelectionExtension.ts
- src/powerbi-visual/src/plugins/viewer.ts
- src/powerbi-visual/src/utils/viewerUtils.ts
Users were still able to click and select ghosted/hidden objects in the viewer which was causing a bad experience when navigating inside the visual.
- Added material visibility filtering
- Implemented isolation state checking
- Only allows selection of objects in the isolatedObjects array
- Let selection extension handle the rest
> fix (visual): disable selection of ghosted objects

- src/powerbi-data-connector/Speckle.pq
- src/powerbi-data-connector/speckle/api/Objects.Properties.pqm
This PR adds multiple improvements to how Objects.Properties helper functions works.
1. Adds parameter group as a suffix instead of a number (_1). It is especially useful when dealing with a large number of properties where there are duplicate property names under different groups. 
It uses a progressive qualification approach:
1. First attempt: Use original field name (e.g., `Width`)
2. First conflict: Add immediate parent (e.g., `Width.Dimensions`)
3. Subsequent conflicts: Add next level up (e.g., `Width.Dimensions.TypeParameters`)
4. Continue: Keep adding hierarchy levels until the name is unique
2. Lists: Array elements are indexed with 1-based numbering now(`Field.1, Field.2`). Previously list values of properties were not handled at all.
3. filterKeys function now returns all …
> Parameter Group as suffix

- src/powerbi-visual/src/settings/visualSettingsModel.ts
- src/powerbi-visual/src/visual.ts
Building option cards removed the built-in Power BI features like conditional formatting, going back to the auto-generation plus our new option card. It's safer.
> fix (visual): bring back the conditional formatting

- src/powerbi-data-connector/Speckle.pq
- src/powerbi-data-connector/speckle/api/Api.Fetch.pqm
- src/powerbi-data-connector/speckle/api/GetModel.pqm
- src/powerbi-data-connector/speckle/api/GetUser.pqm
- src/powerbi-visual/src/store/visualStore.ts
In this PR we're removing personal access token and anonymous (it was from pre-workspace era) authentication methods. Only authentication method will be OAuth. This is done for some security measurements related to token exchange. 
Note: Also there was a small bug about writing receive info to the file, that's fixed.
> feat (data): remove token and anonymous authentication

- src/powerbi-visual/src/store/visualStore.ts
- src/powerbi-visual/src/utils/matrixViewUtils.ts
Implemented a fix for clash between our isolation logic and Power BI conditional formatting. 
`res.shouldColor = true` was forcing colored objects should always be visible and it was overriding cross-filter selection state. Now we apply colors to only visible objects.
> fix (visual): remove forcing conditional formatted objects always be visible
